### ISSUE TITLE
maxinstances: 1 ?

### ISSUE THREAD

**Issue by TomKaltz** [rslvn/nuxt-typescript-ssr-firebase-auth#2]
https://github.com/rslvn/nuxt-typescript-ssr-firebase-auth/blob/550eb721bcd4b6ea26658814caa09e871476be71/functions/src/nuxt-server.ts#L51

Why limit concurrency here?

**Comment by rslvn** [comment]
It does not mean the limit of concurrency. It is the limit of the server instance for the function. If your function has a high load, you can increase it to handle the load.

the `maxInstances` is 1 by default.  It is possible to remove it. It works as-is.

It will be removed from `nuxt-server.ts` and from the other functions too.

Thank you.

**Comment by rslvn** [comment]
removed unnecessary fields from `RuntimeOptions`
